### ISSUE TITLE
File format

### ISSUE THREAD

**Issue by ghost** [ahmaurya/topics_over_time#1]
Hi, I am trying your code. I wonder whether the number before the time in file `alltimes` is necessary? For instance, you have experimented the email data, what is the number in that case? Thank you in advance!

**Comment by ahmaurya** [comment]
Sorry, I have not tried the email dataset. alltimes is used in intializing the data structures when loading the PNAS data. You can find this function in tot.py. You can write your own function to load any dataset that returns the same data structures as the function PNAS dataset.

**Comment by durgeshbhagat** [comment]
Hi Abhinav, 
Can you please explain me first column in alltimes in the pnas_all  datasets. What does the number 18, 19, 14 correspond to ? Does it correspond to number of word in the doc  ? I got this assumption by looking into you code tot.py , line 41, where time stamp for the doc is copied for the corresponding number in the first column.

Thanks,
Durgesh

**Comment by durgeshbhagat** [comment]
I got it in README of PNAS  datasets and referring to http://www.pnas.org/content/by/year/1915 and http://www.pnas.org/content/1/1.toc

Thanks ,
Durgesh
