### ISSUE TITLE
Updating of psi 

### ISSUE THREAD

**Issue by durgeshbhagat** [ahmaurya/topics_over_time#2]
I have following two question regarding updating of parameter psi : 
1. Why 1 is added to psi[i][0] and psi[i][1] in  **GetMethodOfMomentsEstimatesForPsi** apart from other factor mentioned in the paper ?
   psi[i][0] = 1 + timestamp_mean_common_factor
   psi[i][1] = 1 + (1-timestamp_mean)_common_factor
2. Why time stamp  is updated once for every document  rather than updating for each word of every document  in **TopicsOverTimeGibbsSampling** ? 
   
    par['psi'] = self.GetMethodOfMomentsEstimatesForPsi(par)
   Thanks

**Comment by zhiyzuo** [comment]
Same question here: the update of beta dist parameters `psi` is weird. Limiting the two parameters to be larger than 1 will force beta to unimodal. If one of them is 1 then it would be either increasing/decreasing. Using such updates cannot lead to the U-shaped results shown in the original paper. 

Or am I wrong about this?

**Comment by ahmaurya** [comment]
To unblock you guys, I suggest taking a look at FACTORIE released from UMass. It has an implementation of ToT that should be more reliable and correct than this one. I will try to correct this repo when I find the time.
