### ISSUE TITLE
about error

### ISSUE THREAD

**Issue by Naplues** [ahmaurya/topics_over_time#5]
hello,i got a problem like that 
`Traceback (most recent call last):
  File "main_pnas.py", line 44, in <module>
    main()
  File "main_pnas.py", line 33, in main
    documents, timestamps, dictionary = tot.GetPnasCorpusAndDictionary(documents_path, timestamps_path, stopwords_path)
  File "/home/mere/topics_over_time/src/tot.py", line 43, in GetPnasCorpusAndDictionary
    stopwords.update(Set(line.lower().strip().split()))
NameError: name 'Set' is not defined
`

**Comment by ahmaurya** [comment]
This might be because it is run in a particular version of Python which refers to it as set rather than Set. You could try renaming it to set().
